variable "name" {}
variable "location" {}
variable "dsvm_name" {}
variable "dsvm_admin_username" {}
variable "dsvm_host_password" {}
variable "vnet_hub_address_space" {}
variable "jumphost_subnet_address_space" {}
variable "bastion_subnet_address_space" {}
variable "firewall_subnet_address_space" {}
variable "vnet_ml_address_space" {}
variable "vnet_aks_address_space" {}